### ISSUE TITLE
File not found: munro.ttf 

### ISSUE THREAD

**Issue by fanherbaty** [rik-cross/gamma#2]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\gamma-0.4-py3.10.egg\\gamma\\fonts\\munro.ttf'

Kinda weird bug, ill try to fix it and post a pull request so watch out for that

**Comment by fanherbaty** [comment]
Ok so for some reason the 'fonts' folder isnt preasent in the library's path. Probably the problem is just .gitignore

**Comment by rik-cross** [comment]
Hey, thanks for raising the issue. I can see the 'fonts' folder -- did you manage to work out what the issue was?

**Comment by fanherbaty** [comment]
> Hey, thanks for raising the issue. I can see the 'fonts' folder -- did you manage to work out what the issue was?
IDK. Maybe a problem with setuptools. Did you check if it can copy folders?
