### ISSUE TITLE
Text and Circle alpha issue

### ISSUE THREAD

**Issue by Itachi18** [rik-cross/gamma#3]
I was having an issue with text and circles from the examples having a black background.  I'm on a MacBook pro M1.  I wasn't having the issue with Windows.

I went to the draw_utils class and made this change:

def blit_alpha(target, source, location, opacity):
    x = location[0]
    y = location[1]
    temp = pygame.Surface((source.get_width(), source.get_height()), pygame.SRCALPHA)
    temp.blit(target, (-x, -y), special_flags=pygame.BLEND_RGBA_MULT)
    temp.blit(source, (0, 0))
   ## if opacity < 255:
  ##      temp.set_alpha(opacity)
    target.blit(temp, location)
    
   It seems to work properly now on windows and on my mac.  I have a limited understanding of what's going on here, but found some coding examples that showed this concept being executed, so if it doesn't make sense, that's why.

**Comment by rik-cross** [comment]
Thank you so much! I'm on Linux and see the same issue as you do on a Mac.
Happy to update the `blit_alpha` function myself (and credit you), although you're welcome to make a pull request yourself if you prefer.

**Comment by Itachi18** [comment]
I haven’t set up to push and pull, so feel free to update yourself.  I’m glad to help!  I’ve found your tutorials very helpful and well paced, so just wanted to give back if I could.  So thanks!

**Comment by rik-cross** [comment]
Thank you, and glad the tutorials are helpful.

**Comment by Itachi18** [comment]
`def blit_alpha(target, source, location, opacity):`

    x = location[0]
    y = location[1]
    temp = pygame.Surface((source.get_width(), source.get_height()), pygame.SRCALPHA)
    temp.blit(target, (-x, -y), special_flags= pygame.BLEND_RGBA_MULT)
    temp.blit(source, (0, 0))
    if opacity < 255:
        temp.set_alpha(opacity)
    target.blit(temp, location)`

I had some stuff commented out that messed up the formatting, but this seems to be what it ended on.  I think its basically just adding the 2 flags and taking out the convert line.

**Comment by rik-cross** [comment]
Thank you for making the changes so clear.
